#!/usr/bin/env bash

bucket_name="twelve-factor-app-service-staging"
package_name="twelve-factor-config.zip"

# build the application binary
echo "Building binary"
./gradlew build

# package it
echo "Packaging binary and extensions"
rm -rf "$package_name"
zip -j "$package_name" build/libs/*.jar

# stage it
echo "Creating staging bucket if necessary"
[ "$(aws s3api head-bucket --bucket $bucket_name 2>&1 > /dev/null)" ] \
  && (aws s3api create-bucket --bucket "$bucket_name" --region eu-central-1 \
  --create-bucket-configuration LocationConstraint=eu-central-1)
echo "Staging to $bucket_name"
aws s3 cp "$package_name" "s3://$bucket_name"

# spin up / refresh environment
cd cloudformation
./build
