#!/usr/bin/env bash -ex

bucket_name="twelve-factor-app-service-staging"
package_name="twelve-factor-config.zip"
aws_region=$(aws configure get region)

function getBucketRegion {
  echo $(aws s3api get-bucket-location --bucket ${1} | jq .LocationConstraint | tr -d '"')
}
# args (bucketname, region)
function prepareBucket {
  echo "Creating staging bucket if necessary"
  if [ "$(aws s3api head-bucket --bucket $1 2>&1 > /dev/null | echo $?)" == 0 ]
  then
    bucket_region=$(getBucketRegion ${1})
    if [ ${bucket_region} != ${2} ]
    then
      echo "Error: the bucket already exist, but in the other region then you have configured."
      echo "The bucket is exist in the Region: ${bucket_region} !"
      exit 1
    fi
  else
    echo "Info: the bucket does not exist, but will be created in your configured region."
    aws s3api create-bucket --bucket "$1" --region ${2} --create-bucket-configuration LocationConstraint=${2}
  fi
}

# build the application binary
echo "Building binary"
./gradlew build

# package it
echo "Packaging binary and extensions"
rm -rf "$package_name"
zip -j "$package_name" build/libs/*.jar

# stage it
prepareBucket $bucket_name $aws_region
echo "Staging to $bucket_name"
aws s3 cp "$package_name" "s3://$bucket_name"

# spin up / refresh environment
cd cloudformation
./build
