#!/usr/bin/env bash

stack_name="twelve-factor-config-stack"

cloudformation/sg-cleanup DevSecurityGroup
cloudformation/sg-cleanup ProdSecurityGroup

echo "Deleting stack $stack_name..."
aws cloudformation delete-stack --stack-name "$stack_name"
