#!/usr/bin/env bash

stack_name="twelve-factor-config-stack"

cd cloudformation

./sg-cleanup DevSecurityGroup
./sg-cleanup ProdSecurityGroup

echo "Deleting stack $stack_name..."
aws cloudformation delete-stack --stack-name "$stack_name"
