#!/usr/bin/env bash

stack_name="twelve-factor-config-stack"

echo "Building $stack_name..."
aws cloudformation deploy \
  --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND \
  --stack-name $stack_name \
  --template-file config-app.yml
