#!/usr/bin/env bash

stack_name="twelve-factor-config-stack"

echo "Building $stack_name..."
aws cloudformation update-stack \
  --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND \
  --stack-name $stack_name \
  --template-body file://config-app.yml
