#!/usr/bin/env bash

ec_sg_group_id=$(aws ec2 describe-security-groups \
    --filters Name=tag:aws:cloudformation:logical-id,Values="$1" \
    --query "SecurityGroups[*].[GroupId]" \
    --output text)
[ -z "$ec_sg_group_id" ] && exit 0

echo "Removing authorizations from security group $1 ($ec_sg_group_id)"

all_authorizations=$(aws ec2 describe-security-groups \
  --filters Name=tag:aws:cloudformation:logical-id,Values="$1" \
  --query "SecurityGroups[*].IpPermissions[]" \
  --output json)
[ -z "$all_authorizations" ] && exit 0

aws ec2 revoke-security-group-ingress \
  --group-id "$ec_sg_group_id" \
  --ip-permissions "$all_authorizations"

echo "Done."
